In [1]:
# Temel kütüphaneler içe aktarılır.
import numpy as np
import pandas as pd
from sklearn import linear_model

In [6]:
# Veri seti yüklenir.
data = pd.read_csv('homeprices.csv')
# Veriye göz atılır.
data.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
# Sütun adları Türkçeye çevrilmiştir.
data.rename(columns = {'area':'alan', 'bedrooms':'oda_sayisi',
'age':'yasi', 'price':'fiyati'}, inplace = True)
# Veri setine göz atılır.
data.head()

alan  oda_sayisi  yasi  fiyati
0  2600         3.0    20  550000
1  3000         4.0    15  565000
2  3200         NaN    18  610000
3  3600         3.0    30  595000
4  4000         5.0     8  760000

In [8]:
# Veri türleri ve eksik veri bilgisi görüntülenir.
data.info()
# Eksik veri ortanca değer ile tamamlanır.
# Veri setinin özelliğine göre farklı yöntemler kullanılabilir.
median_oda_sayisi = data['oda_sayisi'].median()
median_oda_sayisi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   alan        6 non-null      int64  
 1   oda_sayisi  5 non-null      float64
 2   yasi        6 non-null      int64  
 3   fiyati      6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


4.0

In [9]:
# Eksik veri ortanca değer ile tamamlanır.
# Veri setinin özelliğine göre farklı yöntemler kullanılabilir.
median_oda_sayisi = data['oda_sayisi'].median()
median_oda_sayisi
data.oda_sayisi = data.oda_sayisi.fillna(median_oda_sayisi)
data

alan  oda_sayisi  yasi  fiyati
0  2600         3.0    20  550000
1  3000         4.0    15  565000
2  3200         4.0    18  610000
3  3600         3.0    30  595000
4  4000         5.0     8  760000
5  4100         6.0     8  810000

In [10]:
# Çoklu doğrusal regresyon modeli eğitilir.
# Özellik olarak alan, oda_sayisi ve yasi sütunları seçilir.
# Tahmin edilecek değişken olarak fiyat sütunu belirlenir.
reg = linear_model.LinearRegression()
reg.fit(data[['alan', 'oda_sayisi', 'yasi']], data.fiyati)

LinearRegression()

In [11]:
# Regresyon denklemi sabit ve katsayılar.
print('Sabit (bias): \n', reg.intercept_)
print('Katsayılar: \n', reg.coef_)

Sabit (bias): 
 221323.00186540408
Katsayılar: 
 [  112.06244194 23388.88007794 -3231.71790863]


In [13]:
# Model kullanılarak tahminler yapılır.
reg_pred = reg.predict(data[['alan', 'oda_sayisi', 'yasi']])

In [14]:
# Model değerlendirme metrikleri içe aktarılır.
from sklearn.metrics import mean_squared_error, r2_score
# Ortalama Kare Hata
print("Ortalama Kare Hata: %.2f" % mean_squared_error(data.
fiyati, reg_pred))
# R Kare: 1 mükemmel tahmin.
print("R Kare: %.2f" % r2_score(data.fiyati, reg_pred))

Ortalama Kare Hata: 446305128.22
R Kare: 0.96


In [15]:
reg.predict([[3000,3,40]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [16]:
#Uygulama5
# Temel kütüphaneler içe aktarılır.
import numpy as np # Lineer cebir kütüphanesi.
import pandas as pd # Veri işleme.

In [18]:
# Veri görselleştirme.
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style
# Algoritmalar.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# Model performans değerlendirme metrikleri.
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from random import randrange
import warnings # Uyarılar kapatılır.
warnings.filterwarnings("ignore")

In [19]:
# Veri seti yüklenir.
diyabet_df= pd.read_csv("diabetes.csv")
diyabet_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [20]:
diyabet_df.rename(columns = {'Pregnancies':'gebelik',
'Glucose':'glikoz', 'BloodPressure':'kan_basinci',
'SkinThickness':'cilt_kalinligi', 'Insulin':'insulin',
'BMI':'vki', 'DiabetesPedigreeFunction':'diyabet_fonk',
'Age':'yas', 'Outcome':'sonuc'}, inplace = True)
diyabet_df.head()

gebelik  glikoz  kan_basinci  cilt_kalinligi  insulin   vki  diyabet_fonk  \
0        6     148           72              35        0  33.6         0.627   
1        1      85           66              29        0  26.6         0.351   
2        8     183           64               0        0  23.3         0.672   
3        1      89           66              23       94  28.1         0.167   
4        0     137           40              35      168  43.1         2.288   

   yas  sonuc  
0   50      1  
1   31      0  
2   32      1  
3   21      0  
4   33      1

In [21]:
diyabet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gebelik         768 non-null    int64  
 1   glikoz          768 non-null    int64  
 2   kan_basinci     768 non-null    int64  
 3   cilt_kalinligi  768 non-null    int64  
 4   insulin         768 non-null    int64  
 5   vki             768 non-null    float64
 6   diyabet_fonk    768 non-null    float64
 7   yas             768 non-null    int64  
 8   sonuc           768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [25]:
X = diyabet_df[['gebelik', 'glikoz', 'kan_basinci','cilt_kalinligi', 'insulin', 'vki', 'diyabet_fonk','yas' ]] # bağımsız değişkenler.
y = diyabet_df[['sonuc']] # bağımlı değişken.
# Veri seti eğitim ve test olarak ayrılır.
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)
# Veri setinde sadece değerler alınır.
diyabet_df = diyabet_df.values
diyabet_df

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [26]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

LogisticRegression()

In [28]:
# Test seti kullanılarak tahminler yapılır.
tahminler = logistic_model.predict(X_test)
# Performans Değerlendirmesi.
print("Hata Matrisi")
matris = confusion_matrix(y_test,tahminler)
print(matris)
print("\nSınıflandırma Raporu")
rapor = classification_report(y_test,tahminler)
print(rapor)
lr_accuracy = accuracy_score(y_test, tahminler)
print('Lojistik Regresyon model doğruluğu: {:.2f}%'.format(lr_accuracy*100))

Hata Matrisi
[[141  16]
 [ 35  39]]

Sınıflandırma Raporu
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       157
           1       0.71      0.53      0.60        74

    accuracy                           0.78       231
   macro avg       0.76      0.71      0.73       231
weighted avg       0.77      0.78      0.77       231

Lojistik Regresyon model doğruluğu: 77.92%
